name: razorpay_flutter_template
description: A new Flutter project.
publish_to: "none"
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  razorpay_flutter: ^1.3.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
